name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Smoke test imports
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module('llmseo')
          importlib.import_module('llmseo.cli')
          importlib.import_module('llmseo.web')
          print('smoke-ok')
          PY

      - name: Sample audit run
        run: |
          llm-seo https://example.com --json --max-pages 3 --save-llm-txt --out-dir out > audit.json
          cat audit.json

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sample-audit
          path: |
            audit.json
            out/llm.txt
