name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Smoke test imports
        run: |
          python - <<'PY'
          import importlib
          importlib.import_module('llmseo')
          importlib.import_module('llmseo.cli')
          importlib.import_module('llmseo.web')
          print('smoke-ok')
          PY

